name: Bug Report
description: Report a bug in the syntax
title: '"PATTERN" in `COMMAND`'
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: "Thank you for taking the time to report a bug in `cmd-help`!"
# maybe add dropdown for false positive vs false negative / but we'd have to manually tag anyways...
- type: textarea
  attributes:
    label: description
    description: |
      Please include a screenshot. Otherwise, paste the full line where the bug appears.

      Also, describe your expectations. For instance:

      - "PATTERN" is colorized but it shouldn't
      - "PATTERN" should be colorized because it's an argument
      - "PATTERN" is colorized like arguments but should be colorized like options

  validations:
    required: true
- type: markdown
  attributes:
    value: ":speech_balloon: The following info helps us diagnose the bug."
- type: input
  attributes:
    label: "$ bat --version"
    description: "Which version of `bat` are you running?"
    placeholder: bat 0.23.0
  validations:
    required: true
- type: textarea
  attributes:
    label: "$ COMMAND --help"
    description: "Paste the full help message where the bug appears."
    render: Text # aka: plain text
  validations:
    required: true
- type: input
  attributes:
    label: "$ COMMAND --version"
    description: "Which version of the command are you running?"
    placeholder: "3.1.3"
# maybe add $ bat --diagnostic | grep -i "theme"
